library(readr)
library(magrittr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggthemes)
library(ReporteRs)
library(rstan)
library(rstanarm)
rstan_options(auto_write = TRUE)
options(mc.cores = parallel::detectCores())
setwd("")

rm(list=ls())
source("01-load.R")
source("02-clean.R")

rm(list=ls())
source("03-functions.R")
source("04-analysis/do.R")
source("04-analysis/plot.R")
source("04-analysis/export.R")

rm(list=ls())
source("03-functions.R")
source("05-analysis/do.R")
source("05-analysis/plot.R")
source("05-analysis/export.R")

