library(data.table)
library(magrittr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggthemes)
library(ReporteRs)
setwd("")

rm(list=ls())
source("1-load.R")
source("2-clean.R")

rm(list=ls())
source("3-analysis/functions.R")
source("3-analysis/do.R")
source("3-analysis/plot.R")
source("3-analysis/export.R")

rm(list=ls())
source("4-analysis/functions.R")
source("4-analysis/do.R")
source("4-analysis/plot.R")
source("4-analysis/export.R")

rm(list=ls())
source("5-analysis/functions.R")
source("5-analysis/do.R")
source("5-analysis/plot.R")
source("5-analysis/export.R")

