library(data.table)
library(magrittr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggthemes)
library(ReporteRs)
setwd("")

rm(list=ls())
source("1-load.R")
source("2-clean.R")

rm(list=ls())
source("3-0-functions.R")
source("3-1-do.R")
source("3-2-plot.R")
source("3-3-export.R")

rm(list=ls())
source("4-0-functions.R")
source("4-1-do.R")
source("4-2-plot.R")
source("4-3-export.R")

rm(list=ls())
source("5-0-functions.R")
source("5-1-do.R")
source("5-2-plot.R")
source("5-3-export.R")

